org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=false
org.gradle.workers.max=4
org.gradle.configuration-cache=true

# Fabric (ver https://fabricmc.net/develop). Alineado con el servidor de produccion.
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2
fabric_api_version=0.161.0+26.3

# Librerias del ecosistema Polymer (mismas versiones que corren en produccion)
polymer_version=0.18.2+26.3
sgui_version=2.2.0+26.3

# Mod
mod_version=0.1.0
maven_group=com.purgatorio
